spring:
  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 3000ms  # 연결 타임아웃
      lettuce:
        pool:
          max-active: 8     # 최대 커넥션 수
          max-idle: 8       # 최대 유휴 커넥션 수
          min-idle: 0       # 최소 유휴 커넥션 수
          max-wait: -1ms    # 커넥션 풀이 비었을 때 대기 시간
      password: ${REDIS_PASSWORD}


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    hikari:
      maximum-pool-size: 20        # 기본 10 → 20으로 상향
      minimum-idle: 10             # 최소 유지 커넥션
      connection-timeout: 10000     # 커넥션 대기 5초 (기본 30초는 너무 김)
      max-lifetime: 1800000        # 30분

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        id.new_generator_mappings: true
        format_sql: true
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized